export enum COLOURS {
    BASE_PRIMARY = '#fcc9a7',
    MAIN_PRIMARY = '#fb9a5b',
    ACCENT_PRIMARY = '#F9731C',
    BASE_SECONDARY = '#9AD6FC',
    MAIN_SECONDARY = '#5BBCFB',
    ACCENT_SECONDARY = '#1CA2F9',

    ACCENT_TERTIARY = '#5BFBDA',
    ACCENT_QUATERNARY = '#5B5BFB',

    BLACK = '#000',
    RED = '#ff0000',
}
