version: '3.7'

services:
    server:
        build: .
        ports:
            - '9000:9000'
        environment:
            - DATABASE_HOST=localhost
            - POSTGRES_DB=test
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - DATABASE_PORT=5432
        depends_on:
            - localhost

    localhost:
        image: postgres
        restart: always
        environment:
            - DATABASE_HOST=localhost
            - POSTGRES_DB=test
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '5432:5432'
        volumes:
            - ./data/postgres:/var/lib/postgresql/data

volumes:
    server_node_modules:
