version: '3.7'

services:
    server:
        build: .
        ports:
            - '9000:9000'
        environment:
            - DATABASE_HOST=${DATABASE_HOST}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - DATABASE_PORT=${DATABASE_PORT}
        depends_on:
            - postgresdb

    postgresdb:
        image: postgres
        restart: always
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - '5432:5432'
        volumes:
            - ./data/postgres:/var/lib/postgresql/data

# volumes:
#     server_node_modules:
